apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-stats
spec:
  replicas: 1

  selector:
    matchLabels:
      app: github-stats

  template:
    metadata:
      labels:
        app: github-stats

    spec:
      containers:
        - name: github-stats
          image: ghcr.io/tiecont/github-profile-stats:694c97f3245a934c47098dfa72f0613f2542b77f
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000

          env:
            - name: PORT
              value: "3000"

            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-stats-env
                  key: GITHUB_TOKEN

            - name: GITHUB_USERNAME
              value: "tiecont"

          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30

          resources:
            requests:
              cpu: 20m
              memory: 32Mi

            limits:
              cpu: 200m
              memory: 128Mi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
